# Generated by Django 5.0.1 on 2024-02-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(default='/var/www/default_game.webp', max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('genre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StatsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_player', models.IntegerField()),
                ('time_played', models.IntegerField()),
                ('nb_party', models.IntegerField()),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcendence.game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('sexe', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('token', models.CharField(max_length=50, null=True)),
                ('avatar', models.CharField(default='/var/www/default_avatar.webp', max_length=255)),
                ('status', models.CharField(default='offline', max_length=50)),
                ('date_creation', models.DateTimeField()),
                ('date_last_connection', models.DateTimeField(null=True)),
                ('id_list_friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcendence.listfriends')),
            ],
        ),
        migrations.CreateModel(
            name='StatsUserByGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('looses', models.IntegerField(default=0)),
                ('nb_played', models.IntegerField(default=0)),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcendence.game')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcendence.user')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_full', models.BooleanField(default=False)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('status', models.CharField(default='waiting', max_length=50)),
                ('score', models.IntegerField()),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcendence.game')),
                ('id_looser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser', to='transcendence.user')),
                ('id_user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='transcendence.user')),
                ('id_user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='transcendence.user')),
                ('id_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='transcendence.user')),
            ],
        ),
        migrations.AddField(
            model_name='listfriends',
            name='id_friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='transcendence.user'),
        ),
        migrations.AddField(
            model_name='listfriends',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='transcendence.user'),
        ),
    ]
